country_choices = (
    ("unknown", "Unknown"),
    ("af", "Afghanistan"),
    ("al", "Albania"),
    ("dz", "Algeria"),
    ("as", "American Samoa"),
    ("ad", "Andorra"),
    ("ao", "Angola"),
    ("ai", "Anguilla"),
    ("aq", "Antarctica"),
    ("ag", "Antigua and Barbuda"),
    ("ar", "Argentina"),
    ("am", "Armenia"),
    ("aw", "Aruba"),
    ("au", "Australia"),
    ("at", "Austria"),
    ("az", "Azerbaijan"),
    ("bs", "Bahamas"),
    ("bh", "Bahrain"),
    ("bd", "Bangladesh"),
    ("bb", "Barbados"),
    ("by", "Belarus"),
    ("be", "Belgium"),
    ("bz", "Belize"),
    ("bj", "Benin"),
    ("bm", "Bermuda"),
    ("bt", "Bhutan"),
    ("bo", "Bolivia"),
    ("ba", "Bosnia and Herzegovina"),
    ("bw", "Botswana"),
    ("bv", "Bouvet Island"),
    ("br", "Brazil"),
    ("io", "British Indian Ocean Territory"),
    ("bn", "Brunei Darussalam"),
    ("bg", "Bulgaria"),
    ("bf", "Burkina Faso"),
    ("bi", "Burundi"),
    ("kh", "Cambodia"),
    ("cm", "Cameroon"),
    ("ca", "Canada"),
    ("cv", "Cape Verde"),
    ("ky", "Cayman Islands"),
    ("cf", "Central African Republic"),
    ("td", "Chad"),
    ("cl", "Chile"),
    ("cn", "China"),
    ("cx", "Christmas Island"),
    ("cc", "Cocos (Keeling) Islands"),
    ("co", "Colombia"),
    ("km", "Comoros"),
    ("cg", "Congo"),
    ("cd", "Congo, The Democratic Republic of the"),
    ("ck", "Cook Islands"),
    ("cr", "Costa Rica"),
    ("ci", "Cote D&#39;Ivoire"),
    ("hr", "Croatia"),
    ("cu", "Cuba"),
    ("cy", "Cyprus"),
    ("cz", "Czech Republic"),
    ("dk", "Denmark"),
    ("dj", "Djibouti"),
    ("dm", "Dominica"),
    ("do", "Dominican Republic"),
    ("ec", "Ecuador"),
    ("eg", "Egypt"),
    ("sv", "El Salvador"),
    ("gq", "Equatorial Guinea"),
    ("er", "Eritrea"),
    ("ee", "Estonia"),
    ("et", "Ethiopia"),
    ("fk", "Falkland Islands (Malvinas)"),
    ("fo", "Faroe Islands"),
    ("fj", "Fiji"),
    ("fi", "Finland"),
    ("fr", "France"),
    ("fx", "France, Metropolitan"),
    ("gf", "French Guiana"),
    ("pf", "French Polynesia"),
    ("tf", "French Southern Territories"),
    ("ga", "Gabon"),
    ("gm", "Gambia"),
    ("ge", "Georgia"),
    ("de", "Germany"),
    ("gh", "Ghana"),
    ("gi", "Gibraltar"),
    ("gr", "Greece"),
    ("gl", "Greenland"),
    ("gd", "Grenada"),
    ("gp", "Guadeloupe"),
    ("gu", "Guam"),
    ("gt", "Guatemala"),
    ("gn", "Guinea"),
    ("gw", "Guinea-Bissau"),
    ("gy", "Guyana"),
    ("ht", "Haiti"),
    ("hm", "Heard Island and McDonald Islands"),
    ("va", "Holy See (Vatican City State)"),
    ("hn", "Honduras"),
    ("hk", "Hong Kong"),
    ("hu", "Hungary"),
    ("is", "Iceland"),
    ("in", "India"),
    ("id", "Indonesia"),
    ("ir", "Iran, Islamic Republic of"),
    ("iq", "Iraq"),
    ("ie", "Ireland"),
    ("il", "Israel"),
    ("it", "Italy"),
    ("jm", "Jamaica"),
    ("jp", "Japan"),
    ("jo", "Jordan"),
    ("kz", "Kazakhstan"),
    ("ke", "Kenya"),
    ("ki", "Kiribati"),
    ("kp", "Korea, Democratic People&#39;s Republic of"),
    ("kr", "Korea, Republic of"),
    ("kw", "Kuwait"),
    ("kg", "Kyrgyzstan"),
    ("la", "Lao People&#39;s Democratic Republic"),
    ("lv", "Latvia"),
    ("lb", "Lebanon"),
    ("ls", "Lesotho"),
    ("lr", "Liberia"),
    ("ly", "Libyan Arab Jamahiriya"),
    ("li", "Liechtenstein"),
    ("lt", "Lithuania"),
    ("lu", "Luxembourg"),
    ("mo", "Macao"),
    ("mk", "Macedonia, the Former Yugoslav Republic of"),
    ("mg", "Madagascar"),
    ("my", "Malaysia"),
    ("mv", "Maldives"),
    ("ml", "Mali"),
    ("mt", "Malta"),
    ("mq", "Martinique"),
    ("mr", "Mauritania"),
    ("mu", "Mauritius"),
    ("yt", "Mayotte"),
    ("mx", "Mexico"),
    ("fm", "Micronesia, Federated States of"),
    ("md", "Moldova, Republic of"),
    ("mc", "Monaco"),
    ("mn", "Mongolia"),
    ("ms", "Montserrat"),
    ("ma", "Morocco"),
    ("mz", "Mozambique"),
    ("mm", "Myanmar"),
    ("na", "Namibia"),
    ("np", "Nepal"),
    ("nl", "Netherlands"),
    ("an", "Netherlands Antilles"),
    ("nc", "New Caledonia"),
    ("nz", "New Zealand"),
    ("ni", "Nicaragua"),
    ("ne", "Niger"),
    ("ng", "Nigeria"),
    ("nu", "Niue"),
    ("mp", "Northern Mariana Islands"),
    ("no", "Norway"),
    ("om", "Oman"),
    ("pk", "Pakistan"),
    ("ps", "Palestinian Territory, Occupied"),
    ("pa", "Panama"),
    ("pg", "Papua New Guinea"),
    ("py", "Paraguay"),
    ("pe", "Peru"),
    ("ph", "Philippines"),
    ("pl", "Poland"),
    ("pt", "Portugal"),
    ("pr", "Puerto Rico"),
    ("qa", "Qatar"),
    ("ro", "Romania"),
    ("ru", "Russian Federation"),
    ("rw", "Rwanda"),
    ("kn", "Saint Kitts and Nevis"),
    ("lc", "Saint Lucia"),
    ("vc", "Saint Vincent and the Grenadines"),
    ("ws", "Samoa"),
    ("sm", "San Marino"),
    ("st", "Sao Tome and Principe"),
    ("sa", "Saudi Arabia"),
    ("sn", "Senegal"),
    ("cs", "Serbia and Montenegro"),
    ("sc", "Seychelles"),
    ("sg", "Singapore"),
    ("sk", "Slovakia"),
    ("si", "Slovenia"),
    ("sb", "Solomon Islands"),
    ("za", "South Africa"),
    ("gs", "South Georgia and the South Sandwich Islands"),
    ("es", "Spain"),
    ("lk", "Sri Lanka"),
    ("sd", "Sudan"),
    ("sr", "Suriname"),
    ("sz", "Swaziland"),
    ("se", "Sweden"),
    ("ch", "Switzerland"),
    ("sy", "Syrian Arab Republic"),
    ("tw", "Taiwan, Province of China"),
    ("tz", "Tanzania, United Republic of"),
    ("th", "Thailand"),
    ("tg", "Togo"),
    ("tk", "Tokelau"),
    ("to", "Tonga"),
    ("tt", "Trinidad and Tobago"),
    ("tn", "Tunisia"),
    ("tr", "Turkey"),
    ("tm", "Turkmenistan"),
    ("tc", "Turks and Caicos Islands"),
    ("tv", "Tuvalu"),
    ("ug", "Uganda"),
    ("ua", "Ukraine"),
    ("ae", "United Arab Emirates"),
    ("gb", "United Kingdom"),
    ("us", "United States"),
    ("um", "United States Minor Outlying Islands"),
    ("uy", "Uruguay"),
    ("uz", "Uzbekistan"),
    ("vu", "Vanuatu"),
    ("ve", "Venezuela"),
    ("vn", "Vietnam"),
    ("vg", "Virgin Islands, British"),
    ("vi", "Virgin Islands, U.S."),
    ("wf", "Wallis and Futuna"),
    ("eh", "Western Sahara"),
    ("ye", "Yemen"),
    ("zm", "Zambia"),
    ("zw", "Zimbabwe")
)
